### ISSUE TITLE
Domain issues

### ISSUE THREAD

**Issue by levino** [fuchsbauberlin/fuchsbauberlin.github.io#9]
Morning @KaiNissen ,

what was this about af4df840ef98bac971e58eb3a689b5bf0280e81d ?

Can I help?

**Comment by levino** [comment]
Educated guess: You wanted to enable www.fuchsbauberlin.de which you meanwhile successfully did via a subdomain with a forward to fuchsbauberlin.de, right?

**Comment by KaiNissen** [comment]
@Levino Thanks for watching. Yes, that's part of it. I also wanted to enforce HTTPS, which required me to update DNS records. GitHub's documentation also states, that already defined custom domains should be removed and added again before enabling enforced HTTPS.

Do you consider the settings correct?

**Comment by levino** [comment]
```bash
dig www.fuchsbauberlin.de

; <<>> DiG 9.11.3-1ubuntu1.3-Ubuntu <<>> www.fuchsbauberlin.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17888
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.fuchsbauberlin.de.		IN	A

;; ANSWER SECTION:
www.fuchsbauberlin.de.	14399	IN	CNAME	fuchsbauberlin.de.
fuchsbauberlin.de.	3598	IN	A	185.199.108.153
fuchsbauberlin.de.	3598	IN	A	185.199.111.153
fuchsbauberlin.de.	3598	IN	A	185.199.110.153
fuchsbauberlin.de.	3598	IN	A	185.199.109.153

;; Query time: 49 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jan 15 13:52:21 CET 2019
;; MSG SIZE  rcvd: 128
```

This is correct as far as I can tell. Also ssl encryption works fine. Just a remark: There is not really a point to encrypt the connection to the website because this data is public anyhow. Only if the users put in private / sensible data (like a login or a contact form) one really needs https.

**Comment by KaiNissen** [comment]
Thanks for checking. I agree, that this is probably not much of an issue. But I'm more of an "encrypt everything" guy. Just because you can. And it doesn't hurt. And you send some stuff with the request headers.

**Comment by levino** [comment]
> And it doesn't hurt. And you send some stuff with the request headers.

It is a waste of energy, one could argue. Just saying. But I do agree with you.
